#!/usr/bin/perl
use strict;
use warnings;

use CGI;
my $cgi = CGI->new;

print $cgi->header('text/plain');

my $n = $cgi->param('N');

if ($n) {
   for my $i (1..$n) {
print "$i\n"
}
} else {
    print "Nie znaleziono argumentu na stronie.";
}
