#!/usr/bin/perl  // To jest tzw. "shebang", wskazuje na lokalizację interpretera, który ma zostać użyty do wykonania tego skryptu. W tym przypadku wskazuje na interpreter Perla.

use CGI;    //Importuje moduł CGI, który umożliwia pracę z parametrami przekazywanymi do skryptu przez protokół HTTP.

my $cgi = CGI->new;    //Tworzy nowy obiekt CGI, który będzie używany do przetwarzania danych przesłanych do skryptu przez żądanie HTTP.

# Pobranie parametrów z zapytania
my $text = $cgi->param('text') || '';  # Pierwszy argument - łańcuch znakowy   //Pobiera wartość parametru 'text' przesłanego przez żądanie HTTP i przypisuje ją do zmiennej $text. Jeśli parametr 'text' nie został przesłany, zmienna przyjmuje pustą wartość.
my $multiplier = $cgi->param('multiplier') || 0;  # Drugi argument - liczba powtórzeń

# Utworzenie powielonego łańcucha znakowego
my $result = $text x $multiplier;

# Ustawienie nagłówka HTTP jako typu zawartości tekstowej
print $cgi->header('text/plain');

# Wyświetlenie wyniku
print $result;


//Proszę napisać skrypt CGI, który powiela łańcuch znakowy podany w pierwszym argumencie tyle
razy ile wynosi wartość w drugim argumencie. Na przykład dla wywołania
http://localhost:8080/skrypt.cgi?abc+3, skrypt powinien wyświetlić ,,abcabcabc".
